dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: decideci1
  strategy: git
  api_key:
    secure: dRrS8vOhq+foGGfCUXS8tHy5EiXla3C2jN4UjpP9FRf8wy/6UL8LRUmr2Hmr70T40ICbiENCviSuc/hPjR8UWC7AH1E7IFh40511RBnQ6Og8Td5LycGKZl1yLp3K8kbb68Fy81B0et9RP/kk/VgXDFfI/g3VrLKHOXoGcdRdewl8q2qywb1LMY22M/gu8MGgFcxY1Lpjv1dBVKoHXgpGIi+Su6cSFW+Y2Qev4VCEoOrx4iE+IB8vP5pVljV4LmJtjaL/9onnG4U5/DOJEQ8MZsAehWcTnaShilIELF/c81wiWc8a5rGFtlhZKbwIlMAXgs/J3hT70szeTbnbDlVhk31FhEWHKhl5uBgETiKJtxwAxYuamns2IhkowQQFuzlWVZHGaM7f/0pbhZkCdSvXZFApXyN3qMqiZbhP73uX+1nmI7jXVeMqNZ60u8nCajV2OcoTKlBKehZcNCpV2iwWFrpnx7vdu1WQ/XOMU36SsWPhB55V1192QXc6RQrkwJL+W4a9QzToGlPna3fgEuCN0E8psh8gzT8neO1guI9h2GUqBl4m/uS0xdoby0YDRSc5iPHoN8GlgDrf1eFhtSUnwQKRPHTdqISz3WWgGlyGWfClwoNXdtf1eZyRpTDoMHzwNd6N4BYcr2aaJYzUiIP6YqzVUS6Hu3QH9FVYiRd+g0I=
